baseURL = "http://scottk.mba/"
languageCode = "en-us"
title = "Scott Knight"
copyright = "2023 Scott Knight All rights reserved"
paginate = 5

[author]
  name = "Scott Knight"
  email = "www@knight.mba"

[permalinks]
    blog = "/:filename"

[build]
  writeStats = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 3

[params]
    dateFormat = "Jan 2, 2006"
    description = "Scott Knight's place on the web where he writes about tech, business, life, and anything else he finds interesting or useful."

[taxonomies]
  tag = "tags"

pygmentsCodefences = true
pygmentsStyle = "solarized-light"

enableRobotsTXT = true