baseURL = "http://example.org/"
languageCode = "en-us"
title = "Scott Knight"

[permalinks]
    blog = "/:filename"

[build]
  writeStats = true

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pre = "edit"
    url = "/projects/"
    weight = 3

[params]
    dateFormat = "Jan 2, 2006"
    accentColorPrimary = "#72bf8c"
    linkColor = "#bf727c"
    # homeText = "Test content"

[taxonomies]
  tag = "tags"