baseURL = "http://example.org/"
languageCode = "en-us"
title = "Scott Knight"
copyright = "2023 Scott Knight All rights reserved"
paginate = 5

[author]
  name = "Scott Knight"
  email = "f93@knight.mba"

[permalinks]
    blog = "/:filename"

[build]
  writeStats = true

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
    dateFormat = "Jan 2, 2006"
    accentColorPrimary = "#72bf8c"
    linkColor = "#bf727c"
    # homeText = "Test content"

[taxonomies]
  tag = "tags"